/**
 * Mock Data para desenvolvimento front-end
 * Simula dados de usuários, leads, atividades e metas
 */

import { User, Lead, Activity, Goal, Workspace, Pipeline, PipelineStage } from "./types";

// Usuário mock atual
export const mockCurrentUser: User = {
  id: "user-1",
  email: "joao.silva@exemplo.com",
  name: "João Silva",
  created_at: "2024-01-15T10:00:00Z",
};

// Workspace mock
export const mockWorkspace: Workspace = {
  id: "workspace-1",
  name: "Agência Digital Pro",
  main_service: "Desenvolvimento de sites e apps",
  average_ticket: 15000,
  created_at: "2024-01-15T10:00:00Z",
};

// Pipeline e stages mock
export const mockPipeline: Pipeline = {
  id: "pipeline-1",
  workspace_id: "workspace-1",
  name: "Funil Principal",
  is_default: true,
  created_at: "2024-01-15T10:00:00Z",
};

export const mockStages: PipelineStage[] = [
  { id: "stage-1", pipeline_id: "pipeline-1", name: "Novo", order_index: 0, created_at: "2024-01-15T10:00:00Z" },
  { id: "stage-2", pipeline_id: "pipeline-1", name: "Contato Iniciado", order_index: 1, created_at: "2024-01-15T10:00:00Z" },
  { id: "stage-3", pipeline_id: "pipeline-1", name: "Qualificado", order_index: 2, created_at: "2024-01-15T10:00:00Z" },
  { id: "stage-4", pipeline_id: "pipeline-1", name: "Proposta Enviada", order_index: 3, created_at: "2024-01-15T10:00:00Z" },
  { id: "stage-5", pipeline_id: "pipeline-1", name: "Fechado (Ganho)", order_index: 4, created_at: "2024-01-15T10:00:00Z" },
  { id: "stage-6", pipeline_id: "pipeline-1", name: "Fechado (Perdido)", order_index: 5, created_at: "2024-01-15T10:00:00Z" },
];

// Leads mock
export const mockLeads: Lead[] = [
  {
    id: "lead-1",
    workspace_id: "workspace-1",
    pipeline_id: "pipeline-1",
    pipeline_stage_id: "stage-2",
    owner_id: "user-1",
    name: "Maria Santos",
    email: "maria@empresa.com",
    phone: "(11) 98765-4321",
    company: "Tech Solutions Ltda",
    source_channel: "LinkedIn",
    service_interest: "Desenvolvimento de App Mobile",
    estimated_value: 25000,
    next_step: "Ligar para agendar reunião",
    next_step_date: "2024-11-19T14:00:00Z",
    created_at: "2024-11-15T10:00:00Z",
    updated_at: "2024-11-18T15:30:00Z",
    closed_at: null,
    closed_status: null,
  },
  {
    id: "lead-2",
    workspace_id: "workspace-1",
    pipeline_id: "pipeline-1",
    pipeline_stage_id: "stage-3",
    owner_id: "user-1",
    name: "Carlos Oliveira",
    email: "carlos@startup.com",
    phone: "(21) 97654-3210",
    company: "Startup Inovadora",
    source_channel: "Indicação",
    service_interest: "Site institucional + SEO",
    estimated_value: 12000,
    next_step: "Enviar proposta comercial",
    next_step_date: "2024-11-20T10:00:00Z",
    created_at: "2024-11-10T14:00:00Z",
    updated_at: "2024-11-17T11:20:00Z",
    closed_at: null,
    closed_status: null,
  },
  {
    id: "lead-3",
    workspace_id: "workspace-1",
    pipeline_id: "pipeline-1",
    pipeline_stage_id: "stage-4",
    owner_id: "user-1",
    name: "Ana Paula Costa",
    email: "ana@comercio.com",
    phone: "(11) 96543-2109",
    company: "Comércio Online SP",
    source_channel: "Instagram",
    service_interest: "E-commerce completo",
    estimated_value: 35000,
    next_step: "Aguardando retorno sobre proposta",
    next_step_date: "2024-11-22T09:00:00Z",
    created_at: "2024-11-05T09:00:00Z",
    updated_at: "2024-11-16T16:45:00Z",
    closed_at: null,
    closed_status: null,
  },
  {
    id: "lead-4",
    workspace_id: "workspace-1",
    pipeline_id: "pipeline-1",
    pipeline_stage_id: "stage-1",
    owner_id: "user-1",
    name: "Pedro Almeida",
    email: "pedro@consultoria.com",
    phone: "(31) 95432-1098",
    company: "Consultoria Estratégica",
    source_channel: "Tráfego Pago",
    service_interest: "Landing page para campanha",
    estimated_value: 8000,
    next_step: null,
    next_step_date: null,
    created_at: "2024-11-18T16:00:00Z",
    updated_at: "2024-11-18T16:00:00Z",
    closed_at: null,
    closed_status: null,
  },
  {
    id: "lead-5",
    workspace_id: "workspace-1",
    pipeline_id: "pipeline-1",
    pipeline_stage_id: "stage-5",
    owner_id: "user-1",
    name: "Juliana Ferreira",
    email: "juliana@academia.com",
    phone: "(41) 94321-0987",
    company: "Academia Fitness Pro",
    source_channel: "Instagram",
    service_interest: "App de treinos personalizados",
    estimated_value: 18000,
    next_step: null,
    next_step_date: null,
    closed_at: "2024-11-17T18:00:00Z",
    closed_status: "ganho",
    created_at: "2024-10-25T11:00:00Z",
    updated_at: "2024-11-17T18:00:00Z",
  },
];

// Atividades mock
export const mockActivities: Activity[] = [
  {
    id: "activity-1",
    workspace_id: "workspace-1",
    user_id: "user-1",
    lead_id: "lead-1",
    type: "ligacao",
    title: "Ligação de follow-up",
    description: "Ligar para agendar reunião de alinhamento",
    status: "pendente",
    result: null,
    scheduled_for: "2024-11-19T14:00:00Z",
    completed_at: null,
    created_at: "2024-11-18T10:00:00Z",
  },
  {
    id: "activity-2",
    workspace_id: "workspace-1",
    user_id: "user-1",
    lead_id: "lead-2",
    type: "email",
    title: "Enviar proposta comercial",
    description: "Enviar proposta detalhada com valores e prazos",
    status: "pendente",
    result: null,
    scheduled_for: "2024-11-20T10:00:00Z",
    completed_at: null,
    created_at: "2024-11-17T15:00:00Z",
  },
  {
    id: "activity-3",
    workspace_id: "workspace-1",
    user_id: "user-1",
    lead_id: "lead-3",
    type: "nota",
    title: "Follow-up da proposta",
    description: "Verificar se recebeu e leu a proposta enviada",
    status: "pendente",
    result: null,
    scheduled_for: "2024-11-19T09:00:00Z",
    completed_at: null,
    created_at: "2024-11-16T14:00:00Z",
  },
  {
    id: "activity-4",
    workspace_id: "workspace-1",
    user_id: "user-1",
    lead_id: "lead-1",
    type: "whatsapp",
    title: "Mensagem de boas-vindas",
    description: "Enviar mensagem apresentando a empresa",
    status: "concluida",
    result: "atendeu",
    scheduled_for: "2024-11-18T11:00:00Z",
    completed_at: "2024-11-18T11:15:00Z",
    created_at: "2024-11-18T10:00:00Z",
  },
  {
    id: "activity-5",
    workspace_id: "workspace-1",
    user_id: "user-1",
    lead_id: "lead-5",
    type: "reuniao",
    title: "Reunião de fechamento",
    description: "Reunião para assinar contrato",
    status: "concluida",
    result: "em_negociacao",
    scheduled_for: "2024-11-17T15:00:00Z",
    completed_at: "2024-11-17T16:00:00Z",
    created_at: "2024-11-15T09:00:00Z",
  },
];

// Metas mock
export const mockGoals: Goal[] = [
  {
    id: "goal-1",
    workspace_id: "workspace-1",
    user_id: "user-1",
    type: "leads_por_dia",
    period: "daily",
    target_value: 5,
    created_at: "2024-11-01T10:00:00Z",
  },
  {
    id: "goal-2",
    workspace_id: "workspace-1",
    user_id: "user-1",
    type: "atividades_por_dia",
    period: "daily",
    target_value: 10,
    created_at: "2024-11-01T10:00:00Z",
  },
  {
    id: "goal-3",
    workspace_id: "workspace-1",
    user_id: "user-1",
    type: "negocios_por_mes",
    period: "monthly",
    target_value: 8,
    created_at: "2024-11-01T10:00:00Z",
  },
  {
    id: "goal-4",
    workspace_id: "workspace-1",
    user_id: "user-1",
    type: "receita_por_mes",
    period: "monthly",
    target_value: 120000,
    created_at: "2024-11-01T10:00:00Z",
  },
];

// Stats calculados do mock
export const mockStats = {
  newLeadsToday: 1,
  activeLeads: 3,
  meetingsThisWeek: 2,
  dealsThisMonth: 1,
  revenueThisMonth: 18000,
};
